# 
TARGET = DSC

BIN_DIR=build
LIBSRCS = $(wildcard ../src/*.cpp) $(wildcard ../CGLA/*.cpp) $(wildcard ../is_mesh/*.cpp) $(wildcard ../DEMO/*.cpp) $(wildcard ../SCGenerator/*.cpp) $(wildcard ../TetGen/*.cpp)
LIBC =  $(wildcard ../SOIL/*.c)
LIBOBJS = $(LIBSRCS:.cpp=.o) $(LIBC:.c=.o) 

WARNING= -w
	

CXX = g++
CXXFLAGS = -Wall -O3 -std=c++11 -fpermissive $(WARNING)
CFLAGS= -I ../src -I../CGLA -I../SOIL -I../is_mesh -I../ -I/usr/include -I../CImg -I../SCGenerator -I../TetGen
LDFLAGS = -lm -lGL -L/usr/X11R6/lib -lGLU -lglut -lGLEW -lXi -lXmu -L/usr/lib -lboost_filesystem -lboost_system -lpthread

CC = $(CXX)

all:$(TARGET)
$(TARGET): $(LIBOBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(LIBOBJS)  $(CFLAGS) $(LDFLAGS)
	
%.o : %.cpp
	$(CXX) $(CXXFLAGS)  -c $< -o $@ $(CFLAGS)

.PHONY: clean test
test:
	echo $(LIBSRCS)
clean: 
	rm $(LIBOBJS)
	
depend: $(LIBSRCS) $(LIBC)
	makedepend -Y $(LIBSRCS) $(LIBC) 2> /dev/null
# DO NOT DELETE

../src/DSC.o: ../src/DSC.h ../src/geometry.h ../src/profile.h
../src/DSC.o: ../src/cache.hpp
../src/cache.o: ../src/cache.hpp
../src/geometry.o: ../src/geometry.h
../src/profile.o: ../src/profile.h
../CGLA/ArithSqMat3x3Float.o: ../CGLA/ArithSqMat3x3Float.h
../CGLA/ArithSqMat3x3Float.o: ../CGLA/ExceptionStandard.h ../CGLA/CGLA.h
../CGLA/ArithSqMat3x3Float.o: ../CGLA/Vec3f.h ../CGLA/ArithVec3Float.h
../CGLA/ArithSqMat3x3Float.o: ../CGLA/ArithVecFloat.h ../CGLA/ArithVec.h
../CGLA/ArithSqMat3x3Float.o: ../CGLA/Vec3i.h ../CGLA/ArithVec3Int.h
../CGLA/ArithSqMat3x3Float.o: ../CGLA/ArithVecInt.h ../CGLA/Vec3usi.h
../CGLA/ArithSqMat3x3Float.o: ../CGLA/ArithSqMatFloat.h
../CGLA/ArithSqMat3x3Float.o: ../CGLA/ArithMatFloat.h ../CGLA/Mat3x3f.h
../CGLA/ArithSqMat3x3Float.o: ../CGLA/Mat3x3d.h ../CGLA/Vec3d.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/ArithSqMat4x4Float.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/ExceptionStandard.h ../CGLA/CGLA.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/Vec3f.h ../CGLA/ArithVec3Float.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/ArithVecFloat.h ../CGLA/ArithVec.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/Vec3i.h ../CGLA/ArithVec3Int.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/ArithVecInt.h ../CGLA/Vec3usi.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/Vec3Hf.h ../CGLA/Vec4f.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/ArithVec4Float.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/ArithSqMatFloat.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/ArithMatFloat.h ../CGLA/Mat4x4f.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/Mat4x4d.h ../CGLA/Vec3d.h
../CGLA/ArithSqMat4x4Float.o: ../CGLA/Vec4d.h
../CGLA/ArithVec2Float.o: ../CGLA/Vec2f.h ../CGLA/ArithVec2Float.h
../CGLA/ArithVec2Float.o: ../CGLA/ArithVecFloat.h ../CGLA/ArithVec.h
../CGLA/ArithVec2Float.o: ../CGLA/CGLA.h ../CGLA/Vec2i.h ../CGLA/Vec2d.h
../CGLA/ArithVec2Float.o: ../CGLA/Mat2x2f.h ../CGLA/ArithSqMat2x2Float.h
../CGLA/ArithVec2Float.o: ../CGLA/ExceptionStandard.h
../CGLA/ArithVec2Float.o: ../CGLA/ArithSqMatFloat.h ../CGLA/ArithMatFloat.h
../CGLA/ArithVec2Float.o: ../CGLA/Mat2x2d.h
../CGLA/ArithVec3Float.o: ../CGLA/ArithVec3Float.h ../CGLA/ArithVecFloat.h
../CGLA/ArithVec3Float.o: ../CGLA/ArithVec.h ../CGLA/CGLA.h ../CGLA/Vec3f.h
../CGLA/ArithVec3Float.o: ../CGLA/Vec3i.h ../CGLA/ArithVec3Int.h
../CGLA/ArithVec3Float.o: ../CGLA/ArithVecInt.h ../CGLA/Vec3usi.h
../CGLA/ArithVec3Float.o: ../CGLA/Vec3d.h
../CGLA/Mat3x3d.o: ../CGLA/Mat3x3d.h ../CGLA/CGLA.h ../CGLA/Vec3d.h
../CGLA/Mat3x3d.o: ../CGLA/ArithVec3Float.h ../CGLA/ArithVecFloat.h
../CGLA/Mat3x3d.o: ../CGLA/ArithVec.h ../CGLA/Vec3i.h ../CGLA/ArithVec3Int.h
../CGLA/Mat3x3d.o: ../CGLA/ArithVecInt.h ../CGLA/Vec3usi.h ../CGLA/Vec3f.h
../CGLA/Mat3x3d.o: ../CGLA/ArithSqMat3x3Float.h ../CGLA/ExceptionStandard.h
../CGLA/Mat3x3d.o: ../CGLA/ArithSqMatFloat.h ../CGLA/ArithMatFloat.h
../CGLA/Mat3x3f.o: ../CGLA/Mat3x3f.h ../CGLA/CGLA.h ../CGLA/Vec3f.h
../CGLA/Mat3x3f.o: ../CGLA/ArithVec3Float.h ../CGLA/ArithVecFloat.h
../CGLA/Mat3x3f.o: ../CGLA/ArithVec.h ../CGLA/Vec3i.h ../CGLA/ArithVec3Int.h
../CGLA/Mat3x3f.o: ../CGLA/ArithVecInt.h ../CGLA/Vec3usi.h
../CGLA/Mat3x3f.o: ../CGLA/ArithSqMat3x3Float.h ../CGLA/ExceptionStandard.h
../CGLA/Mat3x3f.o: ../CGLA/ArithSqMatFloat.h ../CGLA/ArithMatFloat.h
../CGLA/Mat4x4d.o: ../CGLA/Mat4x4d.h ../CGLA/ExceptionStandard.h
../CGLA/Mat4x4d.o: ../CGLA/CGLA.h ../CGLA/Vec3d.h ../CGLA/ArithVec3Float.h
../CGLA/Mat4x4d.o: ../CGLA/ArithVecFloat.h ../CGLA/ArithVec.h ../CGLA/Vec3i.h
../CGLA/Mat4x4d.o: ../CGLA/ArithVec3Int.h ../CGLA/ArithVecInt.h
../CGLA/Mat4x4d.o: ../CGLA/Vec3usi.h ../CGLA/Vec3f.h ../CGLA/Vec3Hf.h
../CGLA/Mat4x4d.o: ../CGLA/Vec4f.h ../CGLA/ArithVec4Float.h ../CGLA/Vec4d.h
../CGLA/Mat4x4d.o: ../CGLA/ArithSqMat4x4Float.h ../CGLA/ArithSqMatFloat.h
../CGLA/Mat4x4d.o: ../CGLA/ArithMatFloat.h
../CGLA/Mat4x4f.o: ../CGLA/Mat4x4f.h ../CGLA/ExceptionStandard.h
../CGLA/Mat4x4f.o: ../CGLA/CGLA.h ../CGLA/Vec3f.h ../CGLA/ArithVec3Float.h
../CGLA/Mat4x4f.o: ../CGLA/ArithVecFloat.h ../CGLA/ArithVec.h ../CGLA/Vec3i.h
../CGLA/Mat4x4f.o: ../CGLA/ArithVec3Int.h ../CGLA/ArithVecInt.h
../CGLA/Mat4x4f.o: ../CGLA/Vec3usi.h ../CGLA/Vec3Hf.h ../CGLA/Vec4f.h
../CGLA/Mat4x4f.o: ../CGLA/ArithVec4Float.h ../CGLA/ArithSqMat4x4Float.h
../CGLA/Mat4x4f.o: ../CGLA/ArithSqMatFloat.h ../CGLA/ArithMatFloat.h
../CGLA/TableTrigonometry.o: ../CGLA/TableTrigonometry.h ../CGLA/CGLA.h
../CGLA/Vec2i.o: ../CGLA/Vec2i.h ../CGLA/ArithVec.h ../CGLA/CGLA.h
../CGLA/Vec2i.o: ../CGLA/Vec2f.h ../CGLA/ArithVec2Float.h
../CGLA/Vec2i.o: ../CGLA/ArithVecFloat.h
../CGLA/Vec3f.o: ../CGLA/Vec3f.h ../CGLA/ArithVec3Float.h
../CGLA/Vec3f.o: ../CGLA/ArithVecFloat.h ../CGLA/ArithVec.h ../CGLA/CGLA.h
../CGLA/Vec3f.o: ../CGLA/Vec3i.h ../CGLA/ArithVec3Int.h ../CGLA/ArithVecInt.h
../CGLA/Vec3f.o: ../CGLA/Vec3usi.h ../CGLA/Vec3d.h ../CGLA/Vec3Hf.h
../CGLA/Vec3f.o: ../CGLA/Vec4f.h ../CGLA/ArithVec4Float.h
../CGLA/Vec3i.o: ../CGLA/Vec3i.h ../CGLA/ArithVec3Int.h ../CGLA/ArithVecInt.h
../CGLA/Vec3i.o: ../CGLA/ArithVec.h ../CGLA/CGLA.h ../CGLA/Vec3f.h
../CGLA/Vec3i.o: ../CGLA/ArithVec3Float.h ../CGLA/ArithVecFloat.h
../CGLA/Vec3i.o: ../CGLA/Vec3usi.h ../CGLA/Vec3d.h ../CGLA/Vec3uc.h
../CGLA/eigensolution.o: ../CGLA/eigensolution.h ../CGLA/Mat2x2f.h
../CGLA/eigensolution.o: ../CGLA/Vec2f.h ../CGLA/ArithVec2Float.h
../CGLA/eigensolution.o: ../CGLA/ArithVecFloat.h ../CGLA/ArithVec.h
../CGLA/eigensolution.o: ../CGLA/CGLA.h ../CGLA/Vec2i.h
../CGLA/eigensolution.o: ../CGLA/ArithSqMat2x2Float.h
../CGLA/eigensolution.o: ../CGLA/ExceptionStandard.h
../CGLA/eigensolution.o: ../CGLA/ArithSqMatFloat.h ../CGLA/ArithMatFloat.h
../CGLA/eigensolution.o: ../CGLA/Mat3x3f.h ../CGLA/Vec3f.h
../CGLA/eigensolution.o: ../CGLA/ArithVec3Float.h ../CGLA/Vec3i.h
../CGLA/eigensolution.o: ../CGLA/ArithVec3Int.h ../CGLA/ArithVecInt.h
../CGLA/eigensolution.o: ../CGLA/Vec3usi.h ../CGLA/ArithSqMat3x3Float.h
../CGLA/eigensolution.o: ../CGLA/Mat4x4f.h ../CGLA/Vec3Hf.h ../CGLA/Vec4f.h
../CGLA/eigensolution.o: ../CGLA/ArithVec4Float.h
../CGLA/eigensolution.o: ../CGLA/ArithSqMat4x4Float.h ../CGLA/Mat2x2d.h
../CGLA/eigensolution.o: ../CGLA/Vec2d.h ../CGLA/Mat3x3d.h ../CGLA/Vec3d.h
../CGLA/eigensolution.o: ../CGLA/Mat4x4d.h ../CGLA/Vec4d.h
../CGLA/gel_rand.o: ../CGLA/CGLA.h
../CGLA/statistics.o: ../CGLA/statistics.h ../CGLA/Mat2x2f.h ../CGLA/Vec2f.h
../CGLA/statistics.o: ../CGLA/ArithVec2Float.h ../CGLA/ArithVecFloat.h
../CGLA/statistics.o: ../CGLA/ArithVec.h ../CGLA/CGLA.h ../CGLA/Vec2i.h
../CGLA/statistics.o: ../CGLA/ArithSqMat2x2Float.h
../CGLA/statistics.o: ../CGLA/ExceptionStandard.h ../CGLA/ArithSqMatFloat.h
../CGLA/statistics.o: ../CGLA/ArithMatFloat.h ../CGLA/Mat3x3f.h
../CGLA/statistics.o: ../CGLA/Vec3f.h ../CGLA/ArithVec3Float.h
../CGLA/statistics.o: ../CGLA/Vec3i.h ../CGLA/ArithVec3Int.h
../CGLA/statistics.o: ../CGLA/ArithVecInt.h ../CGLA/Vec3usi.h
../CGLA/statistics.o: ../CGLA/ArithSqMat3x3Float.h ../CGLA/Mat4x4f.h
../CGLA/statistics.o: ../CGLA/Vec3Hf.h ../CGLA/Vec4f.h
../CGLA/statistics.o: ../CGLA/ArithVec4Float.h ../CGLA/ArithSqMat4x4Float.h
../CGLA/statistics.o: ../CGLA/Mat2x2d.h ../CGLA/Vec2d.h ../CGLA/Mat3x3d.h
../CGLA/statistics.o: ../CGLA/Vec3d.h ../CGLA/Mat4x4d.h ../CGLA/Vec4d.h
../is_mesh/mesh_io.o: ../is_mesh/mesh_io.h ../is_mesh/util.h
../is_mesh/mesh_io.o: ../src/geometry.h
../DEMO/demo.o: ../DEMO/user_interface.h ../src/DSC.h ../src/geometry.h
../DEMO/demo.o: ../src/profile.h ../src/cache.hpp ../DEMO/log.h
../DEMO/demo.o: ../DEMO/draw.h ../DEMO/image3d.h ../is_mesh/util.h
../DEMO/demo.o: ../DEMO/segment_function.h
../DEMO/draw_helper.o: ../DEMO/draw_helper.h ../DEMO/image3d.h
../DEMO/draw_helper.o: ../is_mesh/util.h ../src/DSC.h ../src/geometry.h
../DEMO/draw_helper.o: ../src/profile.h ../src/cache.hpp
../DEMO/glut_menu.o: ../DEMO/glut_menu.h
../DEMO/image3d.o: ../DEMO/image3d.h ../is_mesh/util.h
../DEMO/image3d.o: ../DEMO/tet_dis_coord.hpp
../DEMO/log.o: ../DEMO/log.h ../src/DSC.h ../src/geometry.h ../src/profile.h
../DEMO/log.o: ../src/cache.hpp
../DEMO/segment_function.o: ../DEMO/segment_function.h ../DEMO/image3d.h
../DEMO/segment_function.o: ../is_mesh/util.h ../src/DSC.h ../src/geometry.h
../DEMO/segment_function.o: ../src/profile.h ../src/cache.hpp
../DEMO/segment_function.o: ../DEMO/tet_dis_coord.hpp
../DEMO/tet_dis_coord.o: ../DEMO/tet_dis_coord.hpp
../DEMO/user_interface.o: ../DEMO/user_interface.h ../src/DSC.h
../DEMO/user_interface.o: ../src/geometry.h ../src/profile.h ../src/cache.hpp
../DEMO/user_interface.o: ../DEMO/log.h ../DEMO/draw.h ../DEMO/image3d.h
../DEMO/user_interface.o: ../is_mesh/util.h ../DEMO/segment_function.h
../DEMO/user_interface.o: ../DEMO/rotate_function.h
../DEMO/user_interface.o: ../DEMO/average_function.h
../DEMO/user_interface.o: ../DEMO/normal_function.h ../DEMO/draw_helper.h
../DEMO/user_interface.o: ../DEMO/glut_menu.h
../SCGenerator/generator.o: ../is_mesh/mesh_io.h ../is_mesh/util.h
../SCGenerator/generator.o: ../src/geometry.h ../SCGenerator/tetralizer.h
../SCGenerator/tetralizer.o: ../SCGenerator/tetralizer.h ../is_mesh/util.h
../SCGenerator/tetralizer.o: ../src/geometry.h
../TetGen/predicates.o: ../TetGen/tetgen.h
../TetGen/tetgen.o: ../TetGen/tetgen.h
../SOIL/SOIL.o: ../SOIL/SOIL.h ../SOIL/stb_image.h ../SOIL/stb_image_write.h
../SOIL/SOIL.o: ../SOIL/image_helper.h ../SOIL/image_DXT.h
../SOIL/image_DXT.o: ../SOIL/image_DXT.h
../SOIL/image_helper.o: ../SOIL/image_helper.h
../SOIL/stb_image.o: ../SOIL/stb_image.h
